# usage:
# $ docker-compose up # build image, start container and rails
# $ docker-compose run webapp rake … # run command in container
# $ docker-compose build # rebuild image (if the Dockerfile or dependencies changed)

version: "3.8"

services:

  webapp:
    build: '.'
    container_name: 'madek-webapp'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/madek/server/webapp
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://postgres:madek@host.docker.internal:5432/madek_docker?max-pool-size=5}"
      RAILS_ENV: ${RAILS_ENV:-development}
      # RAILS_LOG_LEVEL: debug
      # DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
